### Test GET
GET http://localhost:3000/

### Register AdminRoutes
POST http://localhost:3000/api/admin/register
Content-Type: application/json

{
  "username": "superadmin",
  "email": "admin@example.com",
  "password": "123456"
}

### Login AdminRoutes
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}
